receivers:
  otlp:
    protocols:
      grpc:
      http:

  prometheus:
    config:
      scrape_configs:
        - job_name: 'consul'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:9107']
        - job_name: 'envoy'
          scrape_interval: 10s  
          metrics_path: '/stats/prometheus'
          static_configs:
            - targets: ['localhost:19000']
       
exporters:
  otlp:
    endpoint: https://tempo-prod-12-prod-sa-east-0.grafana.net:443
    headers:
      Authorization: Basic $API_TOKEN_TEMPO

  prometheusremotewrite:
    endpoint: $ENPOINT_PROMETHEUS_REMOTE_WRITE

processors:
  batch:
    timeout: 10s

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]