apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize
generatorOptions:
  disableNameSuffixHash: true
namespace: default
resources:
  - collector-deploy.yaml
  - collector-service.yaml
secretGenerator:
- name: secrets-collector-config
  files:
  - collector-config.yaml
- name: secrets-collector
  envs:
  - secrets.env